<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../EnterpriseKafka.Abstractions/EnterpriseKafka.Abstractions.csproj" />
    <ProjectReference Include="../EnterpriseKafka.Core/EnterpriseKafka.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.9.0" />
  </ItemGroup>
</Project>
